
export const auth = {
  AUTH_LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
  AUTH_LOGIN_ERROR: 'AUTH_LOGIN_ERROR',
  AUTH_LOGIN_PENDING: 'AUTH_LOGIN_PENDING',
  AUTH_LOGOUT_SUCCESS: 'AUTH_LOGOUT_SUCCESS',
  AUTH_LOGOUT_ERROR: 'AUTH_LOGOUT_ERROR',
  AUTH_LOGOUT_PENDING: 'AUTH_LOGOUT_PENDING',
  AUTH_AUTHORIZE_SUCCESS: 'AUTH_AUTHORIZE_SUCCESS',
  AUTH_AUTHORIZE_ERROR: 'AUTH_AUTHORIZE_ERROR',
  AUTH_AUTHORIZE_PENDING: 'AUTH_AUTHORIZE_PENDING',
  AUTH_REGISTER_SUCCESS: 'AUTH_REGISTER_SUCCESS',
  AUTH_REGISTER_ERROR: 'AUTH_REGISTER_ERROR',
  AUTH_REGISTER_PENDING: 'AUTH_REGISTER_PENDING',
}

export const users = {
  GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
  GET_USERS_ERROR: 'GET_USERS_ERROR',
  GET_USERS_PENDING: 'GET_USERS_PENDING',
}

export const pdfs = {
  GET_PDFS_SUCCESS: 'GET_PDFS_SUCCESS',
  GET_PDFS_ERROR: 'GET_PDFS_ERROR',
  GET_PDFS_PENDING: 'GET_PDFS_PENDING',
}

export const pdf = {
  GET_PDF_SUCCESS: 'GET_PDF_SUCCESS',
  GET_PDF_ERROR: 'GET_PDF_ERROR',
  GET_PDF_PENDING: 'GET_PDF_PENDING',
  CREATE_PDF_SUCCESS: 'CREATE_PDF_SUCCESS',
  CREATE_PDF_ERROR: 'CREATE_PDF_ERROR',
  CREATE_PDF_PENDING: 'CREATE_PDF_PENDING',
  EDIT_PDF_SUCCESS: 'EDIT_PDF_SUCCESS',
  EDIT_PDF_ERROR: 'EDIT_PDF_ERROR',
  EDIT_PDF_PENDING: 'EDIT_PDF_PENDING',
  DELETE_PDF_SUCCESS: 'DELETE_PDF_SUCCESS',
  DELETE_PDF_ERROR: 'DELETE_PDF_ERROR',
  DELETE_PDF_PENDING: 'DELETE_PDF_PENDING',
}